project:
  type: book

book:
  title: "计算天体物理学笔记"
  author: "吕天宁"
  date: "9/25/2025"
  chapters:
    - index.qmd
    - computer.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



